"""
library_seed.py — Seeds the 70-query library into SQLite.
Run once on setup. Queries are then editable via the database.
"""
import json
import sqlite3
import os
import sys
sys.path.insert(0, os.path.dirname(__file__))
from database import get_db, init_db

QUERIES = [
# ── C2 (10) ──
("c1","Unsigned Processes on High Ports","Unsigned outbound on non-standard ports","Command-And-Control","All",'["T1571"]','event.category = "network"\nAND event.network.direction = "OUTGOING"\nAND dst.port.number > 1024\nAND dst.port.number NOT IN (3389,5985,5986,8080,8443,443,80)\nAND src.process.signedStatus = "unsigned"\n| columns event.time, endpoint.name, src.process.name, src.process.image.path, dst.ip.address, dst.port.number, src.process.user\n| sort -event.time | limit 500'),
("c2","Outbound Connections Grouped","Grouped outbound — spot unusual destinations","Command-And-Control","All",'["T1071"]','event.category = "network"\nAND event.network.direction = "OUTGOING"\n| group ConnCount = count() by endpoint.name, src.process.name, dst.ip.address\n| sort -ConnCount | limit 200'),
("c3","Unsigned to Rare IPs","Unsigned with outbound grouped by dest","Command-And-Control","All",'["T1071"]','event.category = "network"\nAND event.network.direction = "OUTGOING"\nAND src.process.signedStatus = "unsigned"\n| group Conns = count() by endpoint.name, src.process.name, src.process.image.path, dst.ip.address, dst.port.number\n| sort -Conns | limit 200'),
("c4","DNS Top Talkers — Unsigned","Unsigned processes with most DNS queries","Command-And-Control","All",'["T1071.004"]','event.category = "dns"\nAND src.process.signedStatus = "unsigned"\n| group QCount = count() by endpoint.name, src.process.name, event.dns.request\n| sort -QCount | limit 500'),
("c5","Reverse Shell Indicators","bash -i, nc -e, python socket, socat, mkfifo","Command-And-Control","All",'["T1059"]','event.category = "process"\nAND event.type in:matchcase ("Process Creation")\nAND (\n    src.process.cmdline contains:anycase ("/dev/tcp/")\n    OR src.process.cmdline contains:anycase ("bash -i")\n    OR src.process.cmdline contains:anycase ("nc -e")\n    OR (src.process.cmdline contains:anycase ("python") AND src.process.cmdline contains:anycase ("socket"))\n    OR src.process.cmdline contains:anycase ("socat")\n    OR src.process.cmdline contains:anycase ("mkfifo")\n)\n| columns event.time, endpoint.name, src.process.name, src.process.cmdline, src.process.user, src.process.parent.name\n| sort -event.time | limit 500'),
("c6","LOLBins Outbound","wscript, mshta, regsvr32, certutil outbound","Command-And-Control","Windows",'["T1218"]','event.category = "network"\nAND event.network.direction = "OUTGOING"\nAND src.process.name in:anycase ("wscript.exe","cscript.exe","mshta.exe","regsvr32.exe","rundll32.exe","certutil.exe","bitsadmin.exe","msiexec.exe")\n| columns event.time, endpoint.name, src.process.name, src.process.cmdline, dst.ip.address, dst.port.number\n| sort -event.time | limit 500'),
("c7","DNS Tunneling — Long Domains","DNS queries >50 chars — dnscat2, iodine, DGA","Command-And-Control","All",'["T1071.004"]','event.category = "dns"\nAND event.dns.request matches "^.{50,}$"\n| columns event.time, endpoint.name, src.process.name, event.dns.request\n| sort -event.time | limit 500'),
("c8","HTTP Beaconing Pattern","Periodic HTTP/S from unsigned — C2 beaconing","Command-And-Control","All",'["T1071.001"]','event.category = "network"\nAND event.network.direction = "OUTGOING"\nAND dst.port.number IN (80,443,8080,8443)\nAND src.process.signedStatus = "unsigned"\n| group Beacons = count() by endpoint.name, src.process.name, dst.ip.address, dst.port.number\n| sort -Beacons | limit 200'),
("c9","Non-Browser DNS","DNS from non-browser unsigned processes","Command-And-Control","All",'["T1071.004"]','event.category = "dns"\nAND src.process.name NOT IN ("chrome.exe","firefox.exe","msedge.exe","brave.exe","safari","chrome","firefox")\nAND src.process.signedStatus = "unsigned"\n| group QC = count() by src.process.name, event.dns.request, endpoint.name\n| sort -QC | limit 300'),
("c10","Cobalt Strike Default Ports","Outbound on 50050, 4444, 8443, 2222","Command-And-Control","All",'["T1071","T1573"]','event.category = "network"\nAND event.network.direction = "OUTGOING"\nAND dst.port.number IN (50050,4444,8443,2222,6666,7777,9999)\n| columns event.time, endpoint.name, src.process.name, dst.ip.address, dst.port.number, src.process.user\n| sort -event.time | limit 500'),
# ── Credential Access (8) ──
("ca1","LSASS Memory Access","Non-system accessing lsass — Mimikatz pattern","Credential-Access","Windows",'["T1003.001"]','event.category = "cross_process"\nAND tgt.process.name = "lsass.exe"\nAND src.process.name NOT IN ("csrss.exe","svchost.exe","lsass.exe","services.exe","MsMpEng.exe","SentinelAgent.exe","WerFault.exe")\n| columns event.time, endpoint.name, src.process.name, src.process.image.path, src.process.cmdline, src.process.user, src.process.image.sha256\n| sort -event.time | limit 200'),
("ca2","SAM/SYSTEM Hive Export","reg save for offline credential dump","Credential-Access","Windows",'["T1003.002"]','event.category = "process"\nAND event.type in:matchcase ("Process Creation")\nAND (src.process.cmdline contains:anycase ("save HKLM\\\\SAM") OR src.process.cmdline contains:anycase ("save HKLM\\\\SYSTEM") OR src.process.cmdline contains:anycase ("save HKLM\\\\SECURITY"))\n| columns event.time, endpoint.name, src.process.cmdline, src.process.user\n| sort -event.time | limit 200'),
("ca3","Cloud Metadata SSRF","Querying 169.254.169.254","Credential-Access","All",'["T1552.005"]','event.category = "network"\nAND dst.ip.address = "169.254.169.254"\n| columns event.time, endpoint.name, src.process.name, src.process.cmdline, src.process.user\n| sort -event.time | limit 200'),
("ca4","Credential File Access","SSH keys, .env, .aws/credentials, kubeconfig","Credential-Access","All",'["T1552.001"]','event.category = "file"\nAND (tgt.file.path contains:anycase (".ssh/id_rsa") OR tgt.file.path contains:anycase (".env") OR tgt.file.path contains:anycase (".aws/credentials") OR tgt.file.path contains:anycase (".kube/config"))\nAND src.process.name NOT IN ("sshd","ssh","git","code","vim","kubectl")\n| columns event.time, endpoint.name, src.process.name, tgt.file.path, src.process.user\n| sort -event.time | limit 500'),
("ca5","Browser Credential Store","Login Data, Cookies, key4.db from non-browsers","Credential-Access","All",'["T1539"]','event.category = "file"\nAND (tgt.file.path contains:anycase ("Login Data") OR tgt.file.path contains:anycase ("Cookies") OR tgt.file.path contains:anycase ("cookies.sqlite") OR tgt.file.path contains:anycase ("key4.db"))\nAND src.process.name NOT IN ("chrome.exe","firefox.exe","msedge.exe","brave.exe","chrome","firefox")\n| columns event.time, endpoint.name, src.process.name, tgt.file.path, src.process.user\n| sort -event.time | limit 500'),
("ca6","DCSync Attack","Mimikatz dcsync, secretsdump","Credential-Access","Windows",'["T1003.006"]','event.category = "process"\nAND (src.process.cmdline contains:anycase ("lsadump::dcsync") OR src.process.cmdline contains:anycase ("secretsdump") OR src.process.cmdline contains:anycase ("DsGetNCChanges"))\n| columns event.time, endpoint.name, src.process.cmdline, src.process.user\n| sort -event.time | limit 200'),
("ca7","NTDS.dit Access","AD database file access","Credential-Access","Windows",'["T1003.003"]','event.category = "file"\nAND tgt.file.path contains:anycase ("ntds.dit")\nAND src.process.name NOT IN ("lsass.exe","ntdsutl.exe")\n| columns event.time, endpoint.name, src.process.name, tgt.file.path, src.process.user\n| sort -event.time | limit 200'),
("ca8","Kerberoasting","Rubeus, Invoke-Kerberoast","Credential-Access","Windows",'["T1558.003"]','event.category = "process"\nAND (src.process.cmdline contains:anycase ("Invoke-Kerberoast") OR src.process.cmdline contains:anycase ("Rubeus") OR src.process.cmdline contains:anycase ("kerberoast"))\n| columns event.time, endpoint.name, src.process.cmdline, src.process.user\n| sort -event.time | limit 200'),
# ── Execution (8) ──
("ex1","PowerShell Encoded Command","EncodedCommand, -enc, Base64","Execution","Windows",'["T1059.001"]','event.category = "process"\nAND event.type in:matchcase ("Process Creation")\nAND src.process.name in:anycase ("powershell.exe","pwsh.exe")\nAND (src.process.cmdline contains:anycase ("-encodedcommand") OR src.process.cmdline contains:anycase ("-enc ") OR src.process.cmdline contains:anycase ("frombase64"))\n| columns event.time, endpoint.name, src.process.cmdline, src.process.user, src.process.parent.name, src.process.image.sha256\n| sort -event.time | limit 500'),
("ex2","Office Spawning Scripts","Office → cmd/powershell/wscript — macro","Execution","Windows",'["T1204.002"]','event.category = "process"\nAND event.type in:matchcase ("Process Creation")\nAND src.process.parent.name in:anycase ("winword.exe","excel.exe","powerpnt.exe","outlook.exe","onenote.exe")\nAND src.process.name in:anycase ("cmd.exe","powershell.exe","wscript.exe","cscript.exe","mshta.exe","rundll32.exe")\n| columns event.time, endpoint.name, src.process.parent.name, src.process.name, src.process.cmdline, src.process.user\n| sort -event.time | limit 500'),
("ex3","WMIC Remote Execution","process call create","Execution","Windows",'["T1047"]','event.category = "process"\nAND src.process.name = "wmic.exe"\nAND src.process.cmdline contains:anycase ("process call create")\n| columns event.time, endpoint.name, src.process.cmdline, src.process.user\n| sort -event.time | limit 200'),
("ex4","Cron / At Job Creation","crontab, at — scheduled persistence","Execution","Linux",'["T1053.003"]','event.category = "process"\nAND event.type in:matchcase ("Process Creation")\nAND (src.process.name in:anycase ("crontab","at") OR src.process.cmdline contains:anycase ("/etc/cron"))\n| columns event.time, endpoint.name, src.process.name, src.process.cmdline, src.process.user\n| sort -event.time | limit 500'),
("ex5","Unsigned from Temp/AppData/Downloads","Executables from staging directories","Execution","Windows",'["T1204"]','event.category = "process"\nAND event.type in:matchcase ("Process Creation")\nAND src.process.signedStatus = "unsigned"\nAND (src.process.image.path contains:anycase ("\\\\Temp\\\\") OR src.process.image.path contains:anycase ("\\\\AppData\\\\") OR src.process.image.path contains:anycase ("\\\\Downloads\\\\"))\n| columns event.time, endpoint.name, src.process.name, src.process.image.path, src.process.cmdline, src.process.user, src.process.parent.name, src.process.image.sha256, src.process.storyline.id\n| sort -event.time | limit 1000'),
("ex6","MSBuild / InstallUtil LOLBAS","Build tools for code execution","Execution","Windows",'["T1127.001"]','event.category = "process"\nAND src.process.name in:anycase ("MSBuild.exe","installutil.exe","cmstp.exe","regasm.exe","regsvcs.exe")\n| columns event.time, endpoint.name, src.process.name, src.process.cmdline, src.process.user, src.process.parent.name\n| sort -event.time | limit 300'),
("ex7","Suspicious Script Content","IEX, DownloadString, WebClient in scripts","Execution","All",'["T1059"]','event.category = "command_script"\nAND (cmdScript.content contains:anycase ("Invoke-Expression") OR cmdScript.content contains:anycase ("DownloadString") OR cmdScript.content contains:anycase ("WebClient") OR cmdScript.content contains:anycase ("Start-BitsTransfer"))\n| columns event.time, endpoint.name, src.process.name, cmdScript.applicationName, cmdScript.content, src.process.user\n| sort -event.time | limit 500'),
("ex8","Python/Node Spawning Shells","Supply chain or reverse shell","Execution","All",'["T1059.006"]','event.category = "process"\nAND event.type in:matchcase ("Process Creation")\nAND src.process.parent.name in:anycase ("python.exe","python3","python","node.exe","node")\nAND src.process.name in:anycase ("cmd.exe","powershell.exe","bash","sh")\n| columns event.time, endpoint.name, src.process.parent.name, src.process.name, src.process.cmdline, src.process.user\n| sort -event.time | limit 500'),
# ── Persistence (8) ──
("p1","Registry Run Key Modification","Run/RunOnce persistence","Persistence","Windows",'["T1547.001"]','event.category = "registry"\nAND (registry.keyPath contains:anycase ("\\\\CurrentVersion\\\\Run") OR registry.keyPath contains:anycase ("\\\\CurrentVersion\\\\RunOnce"))\n| columns event.time, endpoint.name, src.process.name, registry.keyPath, registry.value, src.process.user\n| sort -event.time | limit 500'),
("p2","macOS LaunchAgent/Daemon","Plist in LaunchAgents/Daemons","Persistence","macOS",'["T1543.001"]','event.category = "file"\nAND event.type in:matchcase ("File Creation")\nAND (tgt.file.path contains "/LaunchAgents/" OR tgt.file.path contains "/LaunchDaemons/")\n| columns event.time, endpoint.name, src.process.name, tgt.file.path, src.process.user\n| sort -event.time | limit 500'),
("p3","Scheduled Task Registration","schtasks or Task Scheduler","Persistence","Windows",'["T1053.005"]','event.category = "scheduled_task"\nAND event.type in:matchcase ("Task Register")\n| columns event.time, endpoint.name, task.name, task.path, src.process.name, src.process.cmdline, src.process.user\n| sort -event.time | limit 500'),
("p4","Linux Cron File Creation","/etc/cron* or /var/spool/cron","Persistence","Linux",'["T1053.003"]','event.category = "file"\nAND event.type in:matchcase ("File Creation")\nAND (tgt.file.path contains "/etc/cron" OR tgt.file.path contains "/var/spool/cron")\n| columns event.time, endpoint.name, src.process.name, tgt.file.path, src.process.user\n| sort -event.time | limit 500'),
("p5","WMI Event Subscription","Fileless WMI persistence","Persistence","Windows",'["T1546.003"]','event.category = "process"\nAND ((src.process.name = "wmic.exe" AND src.process.cmdline contains:anycase ("__EventConsumer")) OR src.process.cmdline contains:anycase ("Register-WmiEvent"))\n| columns event.time, endpoint.name, src.process.cmdline, src.process.user\n| sort -event.time | limit 200'),
("p6","Windows Service Creation","sc.exe create","Persistence","Windows",'["T1543.003"]','event.category = "process"\nAND src.process.name = "sc.exe"\nAND src.process.cmdline contains:anycase ("create")\n| columns event.time, endpoint.name, src.process.cmdline, src.process.user\n| sort -event.time | limit 300'),
("p7","Startup Folder File Drop","Executable in Startup folder","Persistence","Windows",'["T1547.001"]','event.category = "file"\nAND event.type in:matchcase ("File Creation")\nAND tgt.file.path contains:anycase ("\\\\Start Menu\\\\Programs\\\\Startup\\\\")\n| columns event.time, endpoint.name, src.process.name, tgt.file.path, src.process.user\n| sort -event.time | limit 300'),
("p8","Systemd Service Creation","New systemd service files","Persistence","Linux",'["T1543.002"]','event.category = "file"\nAND event.type in:matchcase ("File Creation")\nAND (tgt.file.path contains "/etc/systemd/system/" OR tgt.file.path contains "/usr/lib/systemd/system/")\n| columns event.time, endpoint.name, src.process.name, tgt.file.path, src.process.user\n| sort -event.time | limit 300'),
# ── Defense Evasion (8) ──
("d1","AMSI Bypass","amsiInitFailed, AmsiUtils","Defense-Evasion","Windows",'["T1562.001"]','event.category = "process"\nAND (src.process.cmdline contains:anycase ("amsiInitFailed") OR src.process.cmdline contains:anycase ("AmsiUtils") OR src.process.cmdline contains:anycase ("amsi.dll") OR (src.process.cmdline contains:anycase ("Set-MpPreference") AND src.process.cmdline contains:anycase ("DisableRealtimeMonitoring")))\n| columns event.time, endpoint.name, src.process.name, src.process.cmdline, src.process.user\n| sort -event.time | limit 200'),
("d2","Process Injection","Unsigned cross-process operations","Defense-Evasion","Windows",'["T1055"]','event.category = "cross_process"\nAND src.process.signedStatus = "unsigned"\nAND src.process.crossProcessOpenProcessCount > 0\n| columns event.time, endpoint.name, src.process.name, tgt.process.name, src.process.user\n| sort -event.time | limit 500'),
("d3","Masquerading — Wrong Path","System processes from non-System32","Defense-Evasion","Windows",'["T1036.005"]','event.category = "process"\nAND event.type in:matchcase ("Process Creation")\nAND src.process.name in:anycase ("svchost.exe","csrss.exe","lsass.exe","services.exe","smss.exe")\nAND NOT src.process.image.path contains:anycase ("\\\\Windows\\\\System32\\\\")\n| columns event.time, endpoint.name, src.process.name, src.process.image.path, src.process.image.sha256\n| sort -event.time | limit 500'),
("d4","ETW Tamper","Disable ETW or stop event tracing","Defense-Evasion","Windows",'["T1562.001"]','event.category = "process"\nAND (src.process.cmdline contains:anycase ("EtwEventWrite") OR src.process.cmdline contains:anycase ("logman stop") OR src.process.cmdline contains:anycase ("Remove-EtwTraceProvider"))\n| columns event.time, endpoint.name, src.process.cmdline, src.process.user\n| sort -event.time | limit 200'),
("d5","Defender Tampering","DisableRealtimeMonitoring, ExclusionPath","Defense-Evasion","Windows",'["T1562.001"]','event.category = "process"\nAND (src.process.cmdline contains:anycase ("DisableRealtimeMonitoring") OR src.process.cmdline contains:anycase ("ExclusionPath") OR src.process.cmdline contains:anycase ("DisableAntiSpyware"))\n| columns event.time, endpoint.name, src.process.cmdline, src.process.user\n| sort -event.time | limit 200'),
("d6","Event Log Clearing","wevtutil cl, Clear-EventLog","Defense-Evasion","Windows",'["T1070.001"]','event.category = "process"\nAND ((src.process.name = "wevtutil.exe" AND src.process.cmdline contains:anycase ("cl")) OR src.process.cmdline contains:anycase ("Clear-EventLog"))\n| columns event.time, endpoint.name, src.process.cmdline, src.process.user\n| sort -event.time | limit 200'),
("d7","DLL Sideloading","Unsigned DLLs outside System32","Defense-Evasion","Windows",'["T1574.001"]','event.category = "file"\nAND event.type in:matchcase ("File Creation")\nAND tgt.file.extension = "dll"\nAND NOT tgt.file.path contains:anycase ("\\\\Windows\\\\System32")\nAND src.process.signedStatus = "unsigned"\n| columns event.time, endpoint.name, src.process.name, tgt.file.path, tgt.file.sha256\n| sort -event.time | limit 500'),
("d8","Timestomping","File timestamp manipulation","Defense-Evasion","Windows",'["T1070.006"]','event.category = "process"\nAND (src.process.cmdline contains:anycase ("timestomp") OR (src.process.name = "powershell.exe" AND src.process.cmdline contains:anycase ("CreationTime") AND src.process.cmdline contains:anycase ("LastWriteTime")))\n| columns event.time, endpoint.name, src.process.cmdline, src.process.user\n| sort -event.time | limit 200'),
# ── Exfiltration (7) ──
("xf1","Cloud Storage Upload","Unsigned to Dropbox, Mega, pastebin","Exfiltration","All",'["T1567.002"]','event.category = "dns"\nAND (event.dns.request contains:anycase ("dropbox.com") OR event.dns.request contains:anycase ("mega.nz") OR event.dns.request contains:anycase ("file.io") OR event.dns.request contains:anycase ("transfer.sh") OR event.dns.request contains:anycase ("pastebin.com"))\nAND src.process.signedStatus = "unsigned"\n| columns event.time, endpoint.name, src.process.name, event.dns.request\n| sort -event.time | limit 500'),
("xf2","High-Volume Outbound","Connection count per process","Exfiltration","All",'["T1048"]','event.category = "network"\nAND event.network.direction = "OUTGOING"\n| group TotalConns = count() by endpoint.name, src.process.name, dst.ip.address, dst.port.number\n| sort -TotalConns | limit 200'),
("xf3","DNS Volume Analysis","High-volume DNS per process","Exfiltration","All",'["T1048.003"]','event.category = "dns"\n| group QCount = count() by endpoint.name, src.process.name\n| sort -QCount | limit 100'),
("xf4","Archive Creation Before Exfil","7z, rar, tar, Compress-Archive","Exfiltration","All",'["T1560.001"]','event.category = "process"\nAND (src.process.name in:anycase ("7z.exe","rar.exe","tar.exe","zip.exe") OR src.process.cmdline contains:anycase ("Compress-Archive"))\n| columns event.time, endpoint.name, src.process.name, src.process.cmdline, src.process.user\n| sort -event.time | limit 500'),
("xf5","Certutil Download/Encode","certutil urlcache or encode","Exfiltration","Windows",'["T1140"]','event.category = "process"\nAND src.process.name = "certutil.exe"\nAND (src.process.cmdline contains:anycase ("urlcache") OR src.process.cmdline contains:anycase ("encode") OR src.process.cmdline contains:anycase ("decode"))\n| columns event.time, endpoint.name, src.process.cmdline, src.process.user\n| sort -event.time | limit 300'),
("xf6","Clipboard Theft","Get-Clipboard","Exfiltration","Windows",'["T1115"]','event.category = "process"\nAND src.process.cmdline contains:anycase ("Get-Clipboard")\n| columns event.time, endpoint.name, src.process.name, src.process.cmdline, src.process.user\n| sort -event.time | limit 200'),
("xf7","Rclone / Cloud Sync","rclone, megasync","Exfiltration","All",'["T1567"]','event.category = "process"\nAND (src.process.name in:anycase ("rclone.exe","rclone","megasync.exe") OR src.process.cmdline contains:anycase ("rclone"))\n| columns event.time, endpoint.name, src.process.name, src.process.cmdline, src.process.user\n| sort -event.time | limit 300'),
# ── Privilege Escalation (6) ──
("pe1","UAC Bypass","fodhelper, eventvwr, sdclt","Privilege-Escalation","Windows",'["T1548.002"]','event.category = "process"\nAND (src.process.parent.name in:anycase ("fodhelper.exe","eventvwr.exe","sdclt.exe") AND src.process.name in:anycase ("cmd.exe","powershell.exe"))\n| columns event.time, endpoint.name, src.process.parent.name, src.process.name, src.process.cmdline, src.process.user\n| sort -event.time | limit 200'),
("pe2","Linux SUID/Sudo Abuse","chmod +s, find -perm","Privilege-Escalation","Linux",'["T1548.001"]','event.category = "process"\nAND (src.process.cmdline contains:anycase ("chmod +s") OR src.process.cmdline contains:anycase ("chmod 4755") OR src.process.cmdline contains:anycase ("find / -perm"))\n| columns event.time, endpoint.name, src.process.cmdline, src.process.user\n| sort -event.time | limit 300'),
("pe3","Named Pipe / Potato Exploits","JuicyPotato, PrintSpoofer, GodPotato","Privilege-Escalation","Windows",'["T1134"]','event.category = "process"\nAND src.process.name in:anycase ("JuicyPotato.exe","RottenPotato.exe","SweetPotato.exe","PrintSpoofer.exe","GodPotato.exe")\n| columns event.time, endpoint.name, src.process.name, src.process.cmdline, src.process.user, src.process.image.sha256\n| sort -event.time | limit 200'),
("pe4","Token Manipulation","runas /savecred, whoami /priv","Privilege-Escalation","Windows",'["T1134.001"]','event.category = "process"\nAND (src.process.cmdline contains:anycase ("runas /savecred") OR src.process.cmdline contains:anycase ("whoami /priv") OR src.process.cmdline contains:anycase ("SeDebugPrivilege"))\n| columns event.time, endpoint.name, src.process.cmdline, src.process.user\n| sort -event.time | limit 200'),
("pe5","Kernel Module Loading","insmod, modprobe — rootkit","Privilege-Escalation","Linux",'["T1547.006"]','event.category = "process"\nAND src.process.name in:anycase ("insmod","modprobe")\n| columns event.time, endpoint.name, src.process.name, src.process.cmdline, src.process.user\n| sort -event.time | limit 200'),
("pe6","Passwd/Shadow Modification","Direct auth file modification","Privilege-Escalation","Linux",'["T1098"]','event.category = "file"\nAND event.type in:matchcase ("File Modification")\nAND (tgt.file.path = "/etc/passwd" OR tgt.file.path = "/etc/shadow" OR tgt.file.path = "/etc/sudoers")\n| columns event.time, endpoint.name, src.process.name, tgt.file.path, src.process.user\n| sort -event.time | limit 200'),
# ── Lateral Movement (6) ──
("lm1","PsExec / Remote Service","PsExec-style remote execution","Lateral-Movement","Windows",'["T1021.002"]','event.category = "process"\nAND (src.process.name in:anycase ("psexec.exe","psexesvc.exe","paexec.exe") OR (src.process.parent.name = "services.exe" AND src.process.cmdline contains:anycase ("cmd.exe /c")))\n| columns event.time, endpoint.name, src.process.name, src.process.cmdline, src.process.user\n| sort -event.time | limit 300'),
("lm2","SMB/RDP/WinRM Connections","Outbound on 445, 3389, 5985","Lateral-Movement","Windows",'["T1021"]','event.category = "network"\nAND event.network.direction = "OUTGOING"\nAND dst.port.number IN (445,139,135,3389,5985,5986,22)\nAND src.process.name NOT IN ("svchost.exe","SentinelAgent.exe","System")\n| group ConnCount = count() by endpoint.name, src.process.name, dst.ip.address, dst.port.number\n| sort -ConnCount | limit 200'),
("lm3","RDP Session Hijacking","tscon.exe","Lateral-Movement","Windows",'["T1563.002"]','event.category = "process"\nAND src.process.name = "tscon.exe"\n| columns event.time, endpoint.name, src.process.cmdline, src.process.user\n| sort -event.time | limit 100'),
("lm4","SSH Lateral — Unusual Processes","SSH from non-standard processes","Lateral-Movement","All",'["T1021.004"]','event.category = "network"\nAND event.network.direction = "OUTGOING"\nAND dst.port.number = 22\nAND src.process.name NOT IN ("ssh","sshd","scp","sftp","git")\n| columns event.time, endpoint.name, src.process.name, dst.ip.address, src.process.user\n| sort -event.time | limit 300'),
("lm5","WMI Lateral Movement","WmiPrvSE spawning cmd/powershell","Lateral-Movement","Windows",'["T1047"]','event.category = "process"\nAND src.process.parent.name = "WmiPrvSE.exe"\nAND src.process.name in:anycase ("cmd.exe","powershell.exe")\n| columns event.time, endpoint.name, src.process.cmdline, src.process.user\n| sort -event.time | limit 200'),
("lm6","Pass-the-Hash / Ticket","sekurlsa::pth, Invoke-TheHash","Lateral-Movement","Windows",'["T1550.002"]','event.category = "process"\nAND (src.process.cmdline contains:anycase ("sekurlsa::pth") OR src.process.cmdline contains:anycase ("Invoke-TheHash") OR src.process.cmdline contains:anycase ("Invoke-SMBExec"))\n| columns event.time, endpoint.name, src.process.cmdline, src.process.user\n| sort -event.time | limit 200'),
# ── Discovery (5) ──
("di1","AD Enumeration","net, nltest, AdFind, BloodHound","Discovery","Windows",'["T1087.002"]','event.category = "process"\nAND ((src.process.name = "net.exe" AND src.process.cmdline contains:anycase ("group")) OR src.process.name in:anycase ("nltest.exe","dsquery.exe","AdFind.exe","bloodhound.exe","sharphound.exe") OR src.process.cmdline contains:anycase ("Get-ADUser"))\n| columns event.time, endpoint.name, src.process.name, src.process.cmdline, src.process.user\n| sort -event.time | limit 500'),
("di2","Port Scanning","High unique dest count from unsigned","Discovery","All",'["T1046"]','event.category = "network"\nAND event.network.direction = "OUTGOING"\nAND src.process.signedStatus = "unsigned"\n| group UniqueIPs = count() by endpoint.name, src.process.name, dst.port.number\n| sort -UniqueIPs | limit 100'),
("di3","System Recon Commands","systeminfo, ipconfig, whoami, tasklist","Discovery","Windows",'["T1082"]','event.category = "process"\nAND src.process.name in:anycase ("systeminfo.exe","hostname.exe","ipconfig.exe","tasklist.exe","whoami.exe","qwinsta.exe")\n| columns event.time, endpoint.name, src.process.name, src.process.cmdline, src.process.user, src.process.parent.name\n| sort -event.time | limit 500'),
("di4","Cloud CLI Discovery","aws, az, gcloud, kubectl","Discovery","All",'["T1580"]','event.category = "process"\nAND (src.process.name in:anycase ("aws","az","gcloud","kubectl") OR src.process.cmdline contains:anycase ("aws sts") OR src.process.cmdline contains:anycase ("gcloud auth"))\n| columns event.time, endpoint.name, src.process.name, src.process.cmdline, src.process.user\n| sort -event.time | limit 300'),
("di5","Linux Recon","/etc/passwd, uname -a, find -perm","Discovery","Linux",'["T1082"]','event.category = "process"\nAND (src.process.cmdline contains:anycase ("/etc/passwd") OR src.process.cmdline contains:anycase ("uname -a") OR src.process.cmdline contains:anycase ("-perm -4000"))\n| columns event.time, endpoint.name, src.process.cmdline, src.process.user\n| sort -event.time | limit 500'),
# ── User Behavior (4) ──
("ub1","Brute Force — Failed Logins","Multiple failed logins per source","User-Behavior","All",'["T1110"]','event.category = "logins"\nAND event.login.isSuccessful = "false"\n| group Fails = count() by endpoint.name, event.login.accountName, src.ip.address\n| sort -Fails | limit 200'),
("ub2","Login from Unusual Processes","Non-standard process login","User-Behavior","All",'["T1078"]','event.category = "logins"\nAND event.login.isSuccessful = "true"\nAND src.process.name NOT IN ("sshd","winlogon.exe","lsass.exe","svchost.exe","login")\n| columns event.time, endpoint.name, src.process.name, event.login.accountName, src.ip.address\n| sort -event.time | limit 200'),
("ub3","Unsigned After-Hours Execution","Unsigned process creation outside business hours","User-Behavior","All",'["T1078"]','event.category = "process"\nAND event.type in:matchcase ("Process Creation")\nAND src.process.signedStatus = "unsigned"\n| columns event.time, endpoint.name, src.process.name, src.process.cmdline, src.process.user\n| sort -event.time | limit 500'),
("ub4","Multi-Endpoint Login","Single user on multiple endpoints","User-Behavior","All",'["T1078"]','event.category = "logins"\nAND event.login.isSuccessful = "true"\n| group LoginCount = count(), Endpoints = distinct(endpoint.name) by event.login.accountName\n| sort -Endpoints | limit 100'),
]


def seed_library():
    init_db()
    conn = get_db()
    count = 0
    for q in QUERIES:
        existing = conn.execute("SELECT id FROM query_library WHERE id=?", (q[0],)).fetchone()
        if not existing:
            conn.execute(
                "INSERT INTO query_library (id, title, description, category, platform, mitre, query) VALUES (?,?,?,?,?,?,?)",
                q
            )
            count += 1
    conn.commit()
    conn.close()
    print(f"Seeded {count} queries ({len(QUERIES)} total in library)")


if __name__ == "__main__":
    seed_library()
